name: 'Enforce Linter'

on:
  push:
    branches:
      - main
      - testnet
      - develop
      - experimental
  pull_request:
    branches:
      - main
      - testnet
      - develop
      - experimental

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.9.0'
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.HOLOGRAPH_GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Lint Check
        run: yarn lint
